version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: fiap-fase1:latest
    container_name: fiap-fase1
    ports:
      - "5000:5000"    # Flask API
      - "8501:8501"    # Streamlit Dashboard
    environment:
      # Variáveis de ambiente de produção
      - FLASK_ENV=production
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY:-chave_padrao_mudar_em_producao}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///site.db}
    volumes:
      # Apenas dados e logs em produção (sem código fonte)
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fiap-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  fiap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16