# ================================================
# Docker Compose - AMBIENTE DE PRODUCAO
# ================================================
# Uso: docker-compose -f docker-compose.prod.yml up --build

services:
  app-prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: fiap-fase1:prod
    container_name: fiap-fase1-prod
    ports:
      - "5000:5000"    # Flask API
      - "8501:8501"    # Streamlit Dashboard
    env_file:
      - .env.prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      # Apenas dados e logs (NAO monta codigo fonte)
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fiap-prod-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  fiap-prod-network:
    driver: bridge
    name: fiap-fase1-prod-network