# ================================================
# Docker Compose - AMBIENTE DE DESENVOLVIMENTO
# ================================================
# Uso: docker-compose -f docker-compose.dev.yml up --build

services:
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: fiap-fase1:dev
    container_name: fiap-fase1-dev
    ports:
      - "5000:5000"    # Flask API
      - "8501:8501"    # Streamlit Dashboard
    env_file:
      - .env.dev
    volumes:
      # Monta codigo fonte para hot-reload
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: sh ./start-dev.sh
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks:
      - fiap-dev-network

networks:
  fiap-dev-network:
    driver: bridge
    name: fiap-fase1-dev-network