version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: fiap-fase1-backend:latest
    container_name: fiap-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./ml_training:/app/ml_training
    command: sh ./start-backend.sh
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    shm_size: "2gb"
    networks:
      - fiap-network

  dd-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: always
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: us5.datadoghq.com
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE_LOGS: "name:dd-agent name:portainer"
    volumes:
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - fiap-network

networks:
  fiap-network:
    driver: bridge
    name: fiap-fase1-network
