"""Update tables new model

Revision ID: 054ad84cd6d6
Revises: abc740b20a1e
Create Date: 2025-10-13 01:21:16.101012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054ad84cd6d6'
down_revision: Union[str, Sequence[str], None] = 'abc740b20a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_books_availability', 'books', ['availability'], unique=False)
    op.create_index('ix_books_category_id', 'books', ['category_id'], unique=False)
    op.create_index('ix_books_price', 'books', ['price'], unique=False)
    op.create_index('ix_books_rating', 'books', ['rating'], unique=False)
    op.create_unique_constraint('uq_books_id', 'books', ['id'])
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_constraint('uq_books_id', 'books', type_='unique')
    op.drop_index('ix_books_rating', table_name='books')
    op.drop_index('ix_books_price', table_name='books')
    op.drop_index('ix_books_category_id', table_name='books')
    op.drop_index('ix_books_availability', table_name='books')
    # ### end Alembic commands ###
