"""add indexes to books table

Revision ID: abc740b20a1e
Revises: 
Create Date: 2025-10-11 23:48:58.636282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc740b20a1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar ENUM apenas se não existir
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'user_role'"
    )).fetchone()
    
    if not result:
        # Criar o ENUM apenas se não existir
        user_role_enum = sa.Enum('admin', 'user', name='user_role')
        user_role_enum.create(connection, checkfirst=True)
    
    # Verificar se tabelas já existem
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'categories' not in existing_tables:
        op.create_table('categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
        op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    
    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
    
    if 'books' not in existing_tables:
        op.create_table('books',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('availability', sa.String(), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('(rating >= 1 AND rating <= 5) OR rating IS NULL', name='check_rating_range'),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id', name='uq_books_id')
        )
        op.create_index('ix_books_availability', 'books', ['availability'], unique=False)
        op.create_index('ix_books_category_id', 'books', ['category_id'], unique=False)
        op.create_index('ix_books_price', 'books', ['price'], unique=False)
        op.create_index('ix_books_rating', 'books', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_rating', table_name='books')
    op.drop_index('ix_books_price', table_name='books')
    op.drop_index('ix_books_category_id', table_name='books')
    op.drop_index('ix_books_availability', table_name='books')
    op.drop_table('books')
    op.drop_table('users')
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
