name: Going Merry API Backend Tests

on:
  push:
  pull_request:
  workflow_dispatch: # Aqui coloquei só para testar manualmente

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry --dev

      - name: Update poetry.lock
        run: poetry lock

      - name: Poetry install libraries
        run: poetry install

      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
