name: Going Merry API Backend Tests

on:
  push:
  pull_request:
  workflow_dispatch: # Aqui coloquei só para testar manualmente

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Poetry install
        uses: pip install poetry

      - name: Poetry install libraries
        uses: poetry install

      - name: Code Coverage
        uses: pytest

      - name: Upload do relatório de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
