name: Going Merry API Backend Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Update poetry.lock
        run: poetry lock

      - name: Poetry install libraries
        run: poetry install

      - name: Run tests with pytest and check coverage
        run: |
          poetry run pytest \
            --cov=app/api/endpoints/v1 \
            --cov=app/controller \
            --cov=app/domain \
            --cov=app/dto \
            --cov=app/repository \
            --cov=app/infrastructure \
            --cov=app/services \
            --cov=app/usecases \
            --cov=app/utils \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=80 \
            --maxfail=1 \
            --disable-warnings \
            -q
